/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateRealmRouteImport } from './routes/api/generate-realm'
import { Route as ApiRealmArtSeedRouteImport } from './routes/api/realm-art/$seed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRealmRoute = ApiGenerateRealmRouteImport.update({
  id: '/api/generate-realm',
  path: '/api/generate-realm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealmArtSeedRoute = ApiRealmArtSeedRouteImport.update({
  id: '/api/realm-art/$seed',
  path: '/api/realm-art/$seed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-realm': typeof ApiGenerateRealmRoute
  '/api/realm-art/$seed': typeof ApiRealmArtSeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-realm': typeof ApiGenerateRealmRoute
  '/api/realm-art/$seed': typeof ApiRealmArtSeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-realm': typeof ApiGenerateRealmRoute
  '/api/realm-art/$seed': typeof ApiRealmArtSeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate-realm' | '/api/realm-art/$seed'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate-realm' | '/api/realm-art/$seed'
  id: '__root__' | '/' | '/api/generate-realm' | '/api/realm-art/$seed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateRealmRoute: typeof ApiGenerateRealmRoute
  ApiRealmArtSeedRoute: typeof ApiRealmArtSeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-realm': {
      id: '/api/generate-realm'
      path: '/api/generate-realm'
      fullPath: '/api/generate-realm'
      preLoaderRoute: typeof ApiGenerateRealmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realm-art/$seed': {
      id: '/api/realm-art/$seed'
      path: '/api/realm-art/$seed'
      fullPath: '/api/realm-art/$seed'
      preLoaderRoute: typeof ApiRealmArtSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateRealmRoute: ApiGenerateRealmRoute,
  ApiRealmArtSeedRoute: ApiRealmArtSeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
